### PR TITLE
bug: cloud-init disable fix

### LINKED ISSUE #272: Trident fails to disable cloud-init networking with cloud-init package is missing
Trident tries to disable cloud-init networking by invoking `disable_cloud_init_networking()`, but this function fail when the `cloud-init` package is missing in the image. This is because `disable_cloud_init_networking()` tries to write to `/etc/cloud/cloud.cfg.d` without first checking if the path exists or cloud-init is included in the image.

We should update Trident to confirm if `cloud-init` is included in the image first and also to check the configuration location path exists.

### PR DESCRIPTION
**Pull request by frhuelsz**
# 🔍 Description
 
Fix #272

Check if directory exists before attempting to create file.

### CODE REVIEW

File: crates/trident/src/subsystems/network.rs [hunk 1]
```diff
@@ -41,9 +42,22 @@ impl Subsystem for NetworkSubsystem {
 }
 
 fn disable_cloud_init_networking() -> Result<(), TridentError> {
-    fs::write(CLOUD_INIT_DISABLE_FILE, CLOUD_INIT_DISABLE_CONTENT)
+    let cloud_init_disable_path = Path::new(CLOUD_INIT_CONFIG_DIR).join(CLOUD_INIT_DISABLE_FILE);
+    if !Path::new(CLOUD_INIT_CONFIG_DIR).exists() {
```
Comment (jiria) [inline crates/trident/src/subsystems/network.rs]: I think this is sufficient to address this bug, but should we have a better handling re package presence detection in general? We could use the cosi manifest now, right?

File: crates/trident/src/subsystems/network.rs [hunk 2]
```diff
@@ -41,9 +42,22 @@ impl Subsystem for NetworkSubsystem {
 }
 
 fn disable_cloud_init_networking() -> Result<(), TridentError> {
```
Comment (bfjelds) [inline crates/trident/src/subsystems/network.rs]: lets add a few UTs

Comment (frhuelsz) [reply crates/trident/src/subsystems/network.rs]: added

**Review by bfjelds — APPROVED** [review]
